import { z } from "zod";

// ── LC launch kit (§5.4 "LC launch kit (M4)", §8 endorsements) ──
// Same conventions as post-set.ts: *Model schemas are what Claude sees (every field required,
// nullable where optional, no length or pattern keywords); the full schemas validate what we store.
// The "ads_export" kind's body belongs to contracts/ads.ts.

export const KIT_KINDS = ["subreddit", "ambassador", "press", "creator", "reply_bank", "ads_export"] as const;
export const KitKind = z.enum(KIT_KINDS);
export type KitKind = z.infer<typeof KitKind>;

/** The kinds this module writes itself (ads_export is generated by the ads module). */
export const GENERATED_KIT_KINDS = ["subreddit", "ambassador", "press", "creator", "reply_bank"] as const;
export const GeneratedKitKind = z.enum(GENERATED_KIT_KINDS);
export type GeneratedKitKind = z.infer<typeof GeneratedKitKind>;

export const KIT_LABELS: Record<KitKind, string> = {
  subreddit: "College subreddit posts",
  ambassador: "Campus ambassador kit",
  press: "Press kit",
  creator: "Creator brief",
  reply_bank: "Reply bank",
  ads_export: "Ads export kit",
};

const ClaimRef = z.string().regex(/^C\d+$/);
const IsoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);

/** SyllaCal's /go/[ref] accepts exactly this (src/lib/referral.ts REFERRAL_REF_RE). */
export const REFERRAL_REF_RE = /^[a-zA-Z0-9_-]{1,64}$/;
/** Reddit community names: 2–21 letters, digits or underscores (without the r/). */
export const SUBREDDIT_RE = /^[A-Za-z0-9_]{2,21}$/;

export const KitIssue = z.object({
  code: z.string(),
  message: z.string(),
  severity: z.enum(["block", "warn"]),
});
export type KitIssue = z.infer<typeof KitIssue>;

// ── what the user types in before generating ──

export const SubredditKitInput = z.object({
  /** Communities the user chose (without r/). Empty = the model proposes candidates to check. */
  communities: z.array(z.string().regex(SUBREDDIT_RE)).max(12),
  /** The day the drafts are due (default: launch day). */
  dueDate: IsoDate.nullable(),
});
export type SubredditKitInput = z.infer<typeof SubredditKitInput>;

export const AmbassadorKitInput = z.object({
  /** One referral link each. `ref` null = made from the name. */
  ambassadors: z.array(z.object({ name: z.string().min(1).max(80), ref: z.string().regex(REFERRAL_REF_RE).nullable() })).max(200),
  /** What ambassadors actually get, in the user's words. Never invented: null leaves a placeholder. */
  reward: z.string().max(400).nullable(),
});
export type AmbassadorKitInput = z.infer<typeof AmbassadorKitInput>;

export const PRESS_OUTLET_TYPES = ["student_newsletter", "campus_paper", "podcast", "other"] as const;
export const PressOutletType = z.enum(PRESS_OUTLET_TYPES);
export type PressOutletType = z.infer<typeof PressOutletType>;

export const PressKitInput = z.object({
  /** Real outlets the user supplied. Without them pitches use [Outlet] / [Editor first name]. */
  targets: z
    .array(
      z.object({
        outlet: z.string().min(1).max(120),
        kind: PressOutletType,
        contactName: z.string().max(80).nullable(),
        email: z.string().email().max(200).nullable(),
      }),
    )
    .max(40),
});
export type PressKitInput = z.infer<typeof PressKitInput>;

export const CreatorKitInput = z.object({
  /** What CJ offers a creator (free plan, a fee…), in his words. Null leaves a placeholder. */
  offer: z.string().max(400).nullable(),
});
export type CreatorKitInput = z.infer<typeof CreatorKitInput>;

export const ReplyBankKitInput = z.object({
  /** Extra questions the user expects on launch day. */
  extraQuestions: z.array(z.string().min(1).max(300)).max(30),
});
export type ReplyBankKitInput = z.infer<typeof ReplyBankKitInput>;

export const KitInputs = z.object({
  subreddit: SubredditKitInput.optional(),
  ambassador: AmbassadorKitInput.optional(),
  press: PressKitInput.optional(),
  creator: CreatorKitInput.optional(),
  reply_bank: ReplyBankKitInput.optional(),
  /** Passed through untouched to the ads module. */
  ads_export: z.record(z.string(), z.unknown()).optional(),
});
export type KitInputs = z.infer<typeof KitInputs>;

// ── shared pieces ──

/** Endorsement disclosure (16 CFR 255): first thing in every caption, said out loud in videos. */
export const KitDisclosure = z.object({
  captionPrefix: z.string().min(1),
  spokenLine: z.string().min(1),
  rules: z.array(z.string().min(1)),
});
export type KitDisclosure = z.infer<typeof KitDisclosure>;

const Edited = { lastEditedBy: z.string().nullable().optional() };

// ── 1. subreddit ──

export const SubredditDraftModel = z.object({
  subreddit: z.string(),
  title: z.string(),
  body: z.string(),
  whyThisFits: z.string(),
  bestTime: z.string(),
  claimRefs: z.array(z.string()),
  likelyNotAllowed: z.boolean(),
});
export const SubredditKitModel = z.object({ drafts: z.array(SubredditDraftModel) });
export type SubredditKitModel = z.infer<typeof SubredditKitModel>;

export const SubredditDraft = z.object({
  subreddit: z.string().regex(SUBREDDIT_RE),
  title: z.string().min(1),
  body: z.string().min(1),
  whyThisFits: z.string(),
  bestTime: z.string(),
  rulesUrl: z.string().url(),
  claimRefs: z.array(ClaimRef),
  likelyNotAllowed: z.boolean(),
  /** True when the model suggested the community (nobody has checked it exists or allows this). */
  proposed: z.boolean(),
  checkNote: z.string().nullable(),
  /** The Copy & open task (assisted_tasks) once the draft passes its checks. */
  assistedTaskId: z.string().uuid().nullable(),
});
export type SubredditDraft = z.infer<typeof SubredditDraft>;

export const SubredditKitBody = z.object({
  schemaVersion: z.literal(1),
  kind: z.literal("subreddit"),
  drafts: z.array(SubredditDraft).min(1),
  assistedTaskIds: z.array(z.string().uuid()),
  ...Edited,
});
export type SubredditKitBody = z.infer<typeof SubredditKitBody>;

// ── 2. ambassador ──

export const KitMessageTemplateModel = z.object({
  channel: z.enum(["dm", "email"]),
  subject: z.string().nullable(),
  text: z.string(),
});
export const AmbassadorKitModel = z.object({
  pitch: z.string(),
  perks: z.array(z.string()),
  templates: z.array(KitMessageTemplateModel),
  postingGuide: z.array(z.string()),
  captionExamples: z.array(z.string()),
  claimRefs: z.array(z.string()),
});
export type AmbassadorKitModel = z.infer<typeof AmbassadorKitModel>;

export const KitMessageTemplate = z.object({
  channel: z.enum(["dm", "email"]),
  subject: z.string().nullable(),
  text: z.string().min(1),
});
export type KitMessageTemplate = z.infer<typeof KitMessageTemplate>;

export const AmbassadorLink = z.object({ name: z.string(), ref: z.string().regex(REFERRAL_REF_RE), url: z.string().url() });
export type AmbassadorLink = z.infer<typeof AmbassadorLink>;

export const AmbassadorKitBody = z.object({
  schemaVersion: z.literal(1),
  kind: z.literal("ambassador"),
  pitch: z.string().min(1),
  perks: z.array(z.string().min(1)),
  templates: z.array(KitMessageTemplate).min(1),
  postingGuide: z.array(z.string().min(1)),
  captionExamples: z.array(z.string().min(1)),
  disclosure: KitDisclosure,
  brandedContentSteps: z.array(z.string().min(1)),
  links: z.array(AmbassadorLink),
  claimRefs: z.array(ClaimRef),
  ...Edited,
});
export type AmbassadorKitBody = z.infer<typeof AmbassadorKitBody>;

// ── 3. press ──

export const PressKitModel = z.object({
  facts: z.array(z.object({ label: z.string(), value: z.string(), claimRefs: z.array(z.string()) })),
  boilerplate: z.string(),
  founderQuote: z.string(),
  pitches: z.array(
    z.object({
      outletType: PressOutletType,
      outlet: z.string(),
      subject: z.string(),
      body: z.string(),
      claimRefs: z.array(z.string()),
    }),
  ),
  assets: z.array(z.object({ assetId: z.string(), label: z.string() })),
  claimRefs: z.array(z.string()),
});
export type PressKitModel = z.infer<typeof PressKitModel>;

export const PressFact = z.object({
  label: z.string().min(1),
  value: z.string().min(1),
  claimRefs: z.array(ClaimRef),
  /** "profile" rows come straight from the product profile (name, price…); "fact" rows from a public claim. */
  source: z.enum(["profile", "fact"]),
});
export type PressFact = z.infer<typeof PressFact>;

export const PressPitch = z.object({
  outletType: PressOutletType,
  outlet: z.string().min(1),
  subject: z.string().min(1),
  body: z.string().min(1),
  claimRefs: z.array(ClaimRef),
});
export type PressPitch = z.infer<typeof PressPitch>;

export const PRESS_PITCH_COUNT = 10;
export const FOUNDER_QUOTE_NOTE = "Edit this: it should be your words.";

export const PressKitBody = z.object({
  schemaVersion: z.literal(1),
  kind: z.literal("press"),
  facts: z.array(PressFact).min(1),
  boilerplate: z.string().min(1),
  founderQuote: z.object({ text: z.string().min(1), editMe: z.boolean(), note: z.string() }),
  assets: z.array(z.object({ assetId: z.string().uuid(), label: z.string(), kind: z.string() })),
  pitches: z.array(PressPitch).min(1),
  claimRefs: z.array(ClaimRef),
  ...Edited,
});
export type PressKitBody = z.infer<typeof PressKitBody>;

// ── 4. creator ──

export const CreatorKitModel = z.object({
  whatItIs: z.string(),
  whatToShow: z.array(z.string()),
  dos: z.array(z.string()),
  donts: z.array(z.string()),
  dmTemplates: z.array(z.object({ text: z.string() })),
  claimRefs: z.array(z.string()),
});
export type CreatorKitModel = z.infer<typeof CreatorKitModel>;

export const CreatorKitBody = z.object({
  schemaVersion: z.literal(1),
  kind: z.literal("creator"),
  whatItIs: z.string().min(1),
  whatToShow: z.array(z.string().min(1)),
  dos: z.array(z.string().min(1)),
  donts: z.array(z.string().min(1)),
  disclosure: KitDisclosure,
  brandedContentSteps: z.array(z.string().min(1)),
  dmTemplates: z.array(z.object({ text: z.string().min(1) })).min(1),
  claimRefs: z.array(ClaimRef),
  ...Edited,
});
export type CreatorKitBody = z.infer<typeof CreatorKitBody>;

// ── 5. reply bank ──

export const ReplyBankModel = z.object({
  replies: z.array(z.object({ trigger: z.string(), reply: z.string(), claimRefs: z.array(z.string()) })),
});
export type ReplyBankModel = z.infer<typeof ReplyBankModel>;

export const KitReply = z.object({ trigger: z.string().min(1), reply: z.string().min(1), claimRefs: z.array(ClaimRef) });
export type KitReply = z.infer<typeof KitReply>;

export const ReplyBankBody = z.object({
  schemaVersion: z.literal(1),
  kind: z.literal("reply_bank"),
  replies: z.array(KitReply).min(1),
  ...Edited,
});
export type ReplyBankBody = z.infer<typeof ReplyBankBody>;

export const LaunchKitBody = z.discriminatedUnion("kind", [SubredditKitBody, AmbassadorKitBody, PressKitBody, CreatorKitBody, ReplyBankBody]);
export type LaunchKitBody = z.infer<typeof LaunchKitBody>;

export const KIT_BODY_SCHEMAS = {
  subreddit: SubredditKitBody,
  ambassador: AmbassadorKitBody,
  press: PressKitBody,
  creator: CreatorKitBody,
  reply_bank: ReplyBankBody,
} as const;

export const KIT_MODEL_SCHEMAS = {
  subreddit: SubredditKitModel,
  ambassador: AmbassadorKitModel,
  press: PressKitModel,
  creator: CreatorKitModel,
  reply_bank: ReplyBankModel,
} as const;

// ── estimate ("Make the launch kit · ~$0.50") ──

export const KitRunEstimate = z.object({
  lines: z.array(z.object({ kind: KitKind, label: z.string(), expectedMicros: z.number().int() })),
  low: z.number().int(),
  expected: z.number().int(),
  high: z.number().int(),
  capMicros: z.number().int(),
});
export type KitRunEstimate = z.infer<typeof KitRunEstimate>;
